### path
@baseUrl = http://localhost:8096

### GET pong
GET {{baseUrl}}/ping HTTP/1.1

### POST insert a partner
POST {{baseUrl}}/partner/insert HTTP/1.1
Content-Type: application/json

{
    "cpfCnpj": 33831453870,
    "name": "Diego Zanetti",
    "telephone": "999 999 999"
}

### GET partner from cpfCnpj
GET {{baseUrl}}/partner/33831453870 HTTP/1.1

### GET bonus of partner from cpfCnpj and bonusId
GET {{baseUrl}}/partner/bonus?cpfCnpj=33831453870&bonusId=37 HTTP/1.1

### PATCH update a partner
PATCH {{baseUrl}}/partner/update HTTP/1.1
Content-Type: application/json

{
    "cpfCnpj": 33831453870,
    "name": "Diego Zanetti",
    "telephone": "999 999 999"
}

### DELETE a partner
DELETE {{baseUrl}}/partner/delete/33831453870 HTTP/1.1